---
id: pushchain
name: Push Chain
summary: Initialize the Push Chain core library in Remix
level: 1
tags:
  - JS
  - Remix
  - PushChain
steps:
  - name: Welcome to Push Chain
    path: 0-welcome
  - name: Deploy Contracts on Push Chain
    path: 1-deploy-contracts
  - name: Send Universal Transaction to Simple Counter Contract
    path: 2-send-universal-transaction
  - name: Universal Account Discovery with Solidity
    path: 3-contract-helpers-solidity
  - name: JavaScript Account Conversion Helpers
    path: 4-utility-functions-js
  - name: Universal Counter Smart Contract
    path: 6-universal-counter-solidity
  - name: Conclusion
    path: 7-conclusion
